# Generated by Django 5.2 on 2025-04-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_district_taluka_cityvillage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityVillage',
        ),
    ]
